language: ruby
rvm:
  - 2.3
env:
  global:
    - secure: kb9JT3noPqUmZ7WIrGLricr0ApOAa/is+hzJQwsXn+Wwdoj2HYXThpAbKmZA7iIzNOmQARDT4VdRLLCi6zCMhoRCJtou28Ezz74IQP1PAdytL5S4K7zceejvRlpjuJADM3xs+J+6/T4QRNfGPmomkZRAeOblj8rFY3G1q4E81L56laAHQX4lFMXFdiywn8aGi7p2Jp82qM3pHaSMDkvGffiFFPcB33P5XMUg5oBluOPb7uYa8HQBrDU7aI/mz85l80OaBae+brwkssUx/ofon18vRPAN1g30ZbW4eDrp4FMBR2EkXrL7fW1iwTfPGwWxn3lKEklrbglIoyx+Z0QEPUILLRUhkyMnrTfCUo/VkGLWMqQp2Rv4/aGlV9/lz5L85sIn/Vv/VRkX89ZC2BJSv3ScFL1DtHPC+bfk4hkq6Ra9vzb+N4w3i6aI7ZiPBCvACiQLJL9oDVj33a1/kHsFW+U1BoepzjPr7SsI0RIPjOo1zK/kf2D6V/dy1GlN5xc035L/k7uOlRRCfBRGR28tXUrfGPDgrsfCrTSD+lyHimpiyZyyawpohhDeNIUUGm0NjHWNEpJn+pwpcqxNAhsnAAQkcn3zWBU2AX8O47fUuuEnEJ7gVGP7OETYL8HMx1qBpOwBXSiMotVCaMuYL7XQIli8YVBXwibUXGzYdchmpsQ=
  matrix:
    - GITHUB_REPO="brucellino/black-panther"
    - GITHUB_REPO="EGI-Foundation/ansible-style-guide"
apt addons: 
before_install:
install:
  - bundle install
before_script:
script:
  - inspec exec .
before_cache:
after_failure:
before_deploy:
deploy:
after_deploy:
after_script:
